export class Pacientes {
  constructor(
    public PA_ID1: string,
    public PA_FIRSTNAME: string,
    public PA_LASTNAME: string,
    public PA_SESURNAME: string,
    public PA_SEX: string,
    public id: string,
    public TIPOIDENTIFICADOR: string,
    public CODTIPOORDEN: string,
    public TIPOORDEN: string,
    public CODPROCEDENCIA: string,
    public PROCEDENCIA: string,
    public CODSERVICIO: string,
    public SERVICIO: string,
    public CODDOCTOR: string,
    public DOCTOR: string,
    public IMPRESORA: string,
    public NUMEROORDEN: string,
    public FECHAORDEN: string,
    public HORAORDEN: string,
    public IDENTIFICADOR: string,
    public NOMBRES: string,
    public APELLIDO: string,
    public SEGUNDOAPELLIDO: string,
    public FECHANACIMIENTO: string,
    public SEXO: string,
    public OBSERVACIONES: string,
    public ESTADO: string,
  ) {}
}
